### ISSUE TITLE
Tagasiside kodukakasutajalt

### ISSUE THREAD

**Issue by mitselek** [argoroots/kogumelugu#33]
- [ ] 1. Kui ma videoteeki alalehele lähen, siis võiks seal vaikimisi kõik videod näha olla (või nt esimesd 20 thumbnaili kõikidest). Hetkel ootab mind seal ees suur tühjus ma ma olen segaduses, et mis nüüd. Saan aru, tehniliselt hakkan siis filtreid peale laduma, aga abirattad oleks head. #36
- [x] 2. Mingitele thumbnailidele vajutades saan sellise teate: "Tähelepanu! Proovisid vaadata täispikka intervjuud, kuid selle jaoks pead olema sisselogitud." Aga kust ma tean, millised on täispikad ja millised lühikesed? #37 
- [ ] 3. ~~See veateade võiks ilmuda hoiatuskastikesena või modalina, mitte eraldi lehena, kus tuleb back nuppu vajutada. ei mõju navigeerimisele hästi.~~ => Ei tee
- [x] 4. Embedded video mängitamine on natuke keberniit, kuna saan ainult pausile panna või mängima panna. Aga mis siis, kui tahan seda natuke edasi või tagasi kerida? => Videod lähevad kõik vimeosse, seal on kerimine olemas
- [x] 5. Mingitel hetkedel kerib leht ennast allapoole, ilma et ma seda tahaks või päris sellesuunalist juhist annaks. #32 
- [ ] 6. Random idee + Kui ma videot mängin, siis võiks see avaneda mingis kastis või lightboxis, ilme et seal all olev thumbnailide kogu allapoole läheks. Siis saan mõnusalt akna kinni panna ja kohe edasi navigeerida. => Võib-olla. Samas pole see primaarne, kui #38 korda saab.
- [ ] 7. Kas ajalooõpetajad testivad ka seda süsteemi? Soovitaks nüüd kiiresti minna 4-5 ajalooõpsi juurde, neil paluda seda kasutada ja siis nende tagasiside pealt edasi töötada. Reaalsetelt kasutajatelt saab ikka kõige reaalsemat inffi.. => veidi hiljem testivad
